apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ngz1s6q23-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ngz1s6q23-go 
  name: ngz1s6q23-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ngz1s6q23-go 
